name = "morpheus-control-plane"
main = "worker.mjs"
compatibility_date = "2026-03-20"
account_id = "bf0d7e814f69945157f30505e9fba9fe"
workers_dev = true

[vars]
SUPABASE_URL = "https://przhhxbovqwopibssjzr.supabase.co"
UPSTASH_REDIS_REST_URL = "https://major-sawfish-77541.upstash.io"
MORPHEUS_MAINNET_EXECUTION_BASE_URL = "https://ddff154546fe22d15b65667156dd4b7c611e6093-3000.dstack-pha-prod5.phala.network/mainnet,https://oracle.meshmini.app/mainnet,https://edge.meshmini.app/mainnet"
MORPHEUS_TESTNET_EXECUTION_BASE_URL = "https://ddff154546fe22d15b65667156dd4b7c611e6093-3000.dstack-pha-prod5.phala.network/testnet,https://oracle.meshmini.app/testnet,https://edge.meshmini.app/testnet"
MORPHEUS_APP_BACKEND_URL = "https://neo-morpheus-oracle-web.vercel.app"
MORPHEUS_CONTROL_PLANE_URL = "https://control.meshmini.app"

[[queues.producers]]
binding = "MORPHEUS_ORACLE_REQUEST_QUEUE"
queue = "morpheus-oracle-request"

[[queues.producers]]
binding = "MORPHEUS_FEED_TICK_QUEUE"
queue = "morpheus-feed-tick"

[[queues.producers]]
binding = "MORPHEUS_CALLBACK_BROADCAST_QUEUE"
queue = "morpheus-callback-broadcast"

[[queues.producers]]
binding = "MORPHEUS_AUTOMATION_EXECUTE_QUEUE"
queue = "morpheus-automation-execute"

[[queues.consumers]]
queue = "morpheus-oracle-request"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 10

[[queues.consumers]]
queue = "morpheus-feed-tick"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 10

[[queues.consumers]]
queue = "morpheus-callback-broadcast"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 10

[[queues.consumers]]
queue = "morpheus-automation-execute"
max_batch_size = 10
max_batch_timeout = 5
max_retries = 10

[[routes]]
pattern = "control.meshmini.app/*"
zone_name = "meshmini.app"
