name = "morpheus-edge-gateway"
main = "worker.mjs"
compatibility_date = "2026-03-19"
account_id = "bf0d7e814f69945157f30505e9fba9fe"
workers_dev = true

[vars]
MORPHEUS_ORIGIN_URL = "https://morpheus.meshmini.app"
MORPHEUS_MAINNET_ORIGIN_URL = "https://morpheus.meshmini.app/mainnet"
MORPHEUS_TESTNET_ORIGIN_URL = "https://morpheus.meshmini.app/testnet"
UPSTASH_REDIS_REST_URL = "https://major-sawfish-77541.upstash.io"

[[routes]]
pattern = "edge.meshmini.app/*"
zone_name = "meshmini.app"

[[routes]]
pattern = "morpheus-testnet.meshmini.app/*"
zone_name = "meshmini.app"
