"use client";

import { CheckCircle, Shield, Cpu, Lock, Info } from "lucide-react";

export default function DocsVerifier() {
  return (
    <div className="fade-in">
      <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "1rem" }}>
        <CheckCircle size={14} color="var(--neo-green)" />
        <span style={{ fontSize: '0.7rem', fontWeight: 800, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.1em', fontFamily: 'var(--font-mono)' }}>SECURITY SPEC v1.0.2</span>
      </div>
      <h1>Attestation & Security</h1>

      <p>
        Remote Attestation is the cornerstone of Morpheus's trust model. It allows external observers to cryptographically prove that a piece of software is running inside a genuine hardware enclave (Intel SGX) and that the enclave has not been tampered with.
      </p>

      <h2>The Evidence Layer</h2>
      <p>
        Every task executed by a Morpheus worker can be bundled with an <strong>Attestation Quote</strong>. This quote includes:
      </p>
      <ul>
        <li><strong>MR_ENCLAVE:</strong> A hash of the enclave's initial state (the code and configuration).</li>
        <li><strong>MR_SIGNER:</strong> A hash of the public key that signed the enclave metadata.</li>
        <li><strong>Report Data:</strong> A commitment to the specific output or public key generated by the enclave.</li>
      </ul>

      <h2>Off-Chain Verification Flow</h2>
      <p>
        While on-chain contracts verify the worker's signature, high-security applications should perform off-chain quote verification:
      </p>
      <ol>
        <li>Fetch the <code>attestation</code> object from the Oracle response.</li>
        <li>Verify the quote against Intel's Root Certificate Authority (via Phala's PCCS).</li>
        <li>Check that the <code>MR_ENCLAVE</code> matches the officially released Morpheus binary hash.</li>
        <li>Ensure the <code>report_data</code> contains the hash of the expected result or public key.</li>
      </ol>

      <div style={{ margin: '2.5rem 0', padding: '1.5rem', background: '#000', border: '1px solid var(--border-dim)', borderRadius: '4px' }}>
        <div style={{ fontSize: '0.7rem', color: 'var(--text-muted)', fontWeight: 800, marginBottom: '1rem', fontFamily: 'var(--font-mono)' }}>VERIFIER TOOL</div>
        <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
          Morpheus provides a built-in <strong>Attestation Verifier</strong> in the Matrix Explorer. You can paste any worker response to validate its hardware proof instantly.
        </p>
        <button className="btn btn-secondary btn-sm">OPEN VERIFIER</button>
      </div>

      <h2>Trust Boundaries</h2>
      <p>
        By combining hardware isolation with cryptographic proof, Morpheus shifts the security boundary from <strong>"Trust the Operator"</strong> to <strong>"Trust the Code"</strong>. 
      </p>
      
      <div className="card-industrial" style={{ marginTop: '4rem', padding: '2rem', border: '1px solid var(--border-dim)' }}>
        <div style={{ display: 'flex', gap: '1rem', alignItems: 'center', marginBottom: '1rem' }}>
          <Shield size={20} color="var(--neo-green)" />
          <h4 style={{ fontSize: '1rem', fontWeight: 800, margin: 0, color: '#fff' }}>Auditability</h4>
        </div>
        <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)', marginBottom: 0 }}>
          The entire Morpheus worker runtime is open-source. Security auditors can independent verify that the code running inside the TEE does not contain backdoors and strictly enforces privacy policies.
        </p>
      </div>
    </div>
  );
}
